//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EduadminCoursePortal.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SharedResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EduadminCoursePortal.Resources.SharedResources", typeof(SharedResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avbryt.
        /// </summary>
        internal static string Abort {
            get {
                return ResourceManager.GetString("Abort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frånvarande.
        /// </summary>
        internal static string Absent {
            get {
                return ResourceManager.GetString("Absent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lägg till som deltagare.
        /// </summary>
        internal static string AddAsParticipant {
            get {
                return ResourceManager.GetString("AddAsParticipant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional.
        /// </summary>
        internal static string Additional {
            get {
                return ResourceManager.GetString("Additional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (+{0} namnlösa).
        /// </summary>
        internal static string AddNameLess {
            get {
                return ResourceManager.GetString("AddNameLess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lägg till deltagare.
        /// </summary>
        internal static string AddParticipant {
            get {
                return ResourceManager.GetString("AddParticipant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adress.
        /// </summary>
        internal static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alla deltagare är namnlösa.
        /// </summary>
        internal static string AllParticipantsNameLess {
            get {
                return ResourceManager.GetString("AllParticipantsNameLess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Alla platser -.
        /// </summary>
        internal static string AllPlaces {
            get {
                return ResourceManager.GetString("AllPlaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ett fel uppstod..
        /// </summary>
        internal static string AnErrorHasOccurred {
            get {
                return ResourceManager.GetString("AnErrorHasOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ett fel har inträffat.
        /// </summary>
        internal static string AnErrorOccurred {
            get {
                return ResourceManager.GetString("AnErrorOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ansökningsmetod.
        /// </summary>
        internal static string ApplicationMethod {
            get {
                return ResourceManager.GetString("ApplicationMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Är du säker?.
        /// </summary>
        internal static string AreYouSure {
            get {
                return ResourceManager.GetString("AreYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minst en deltagare måste vara vald.
        /// </summary>
        internal static string AtLeastOneParticipant {
            get {
                return ResourceManager.GetString("AtLeastOneParticipant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Närvaroregistrering.
        /// </summary>
        internal static string AttendanceRegistration {
            get {
                return ResourceManager.GetString("AttendanceRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Närvaro har uppdaterats..
        /// </summary>
        internal static string AttendanceUpdated {
            get {
                return ResourceManager.GetString("AttendanceUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Närvarande.
        /// </summary>
        internal static string Attending {
            get {
                return ResourceManager.GetString("Attending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Närvarande {0}/{1}.
        /// </summary>
        internal static string AttendingAmount {
            get {
                return ResourceManager.GetString("AttendingAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to på obestämd ort.
        /// </summary>
        internal static string AtUnknownLocation {
            get {
                return ResourceManager.GetString("AtUnknownLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tillbaka.
        /// </summary>
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boka.
        /// </summary>
        internal static string Book {
            get {
                return ResourceManager.GetString("Book", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bokningen innehåller redan inbokade deltagare.
        /// </summary>
        internal static string BookingContainsBookedParticipants {
            get {
                return ResourceManager.GetString("BookingContainsBookedParticipants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bokningen innehåller deltagare som redan är inbokade på överlappande delmoment.
        /// </summary>
        internal static string BookingContainsOverlapPersons {
            get {
                return ResourceManager.GetString("BookingContainsOverlapPersons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bokning skapad.
        /// </summary>
        internal static string BookingCreated {
            get {
                return ResourceManager.GetString("BookingCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bokningen misslyckades och ett fel uppstod när felmeddelanden skulle visas. Prova att ladda om sidan och försök igen..
        /// </summary>
        internal static string BookingFailedReloadPage {
            get {
                return ResourceManager.GetString("BookingFailedReloadPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bokningen gäller för.
        /// </summary>
        internal static string BookingFor {
            get {
                return ResourceManager.GetString("BookingFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tillfället är inte bokningsbart längre, tiden för anmälan har passerat..
        /// </summary>
        internal static string BookingLastDayPassedError {
            get {
                return ResourceManager.GetString("BookingLastDayPassedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bokningslänken är inte giltig..
        /// </summary>
        internal static string BookingLinkInvalid {
            get {
                return ResourceManager.GetString("BookingLinkInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bokningsnummer.
        /// </summary>
        internal static string BookingNumber {
            get {
                return ResourceManager.GetString("BookingNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tack för din bokning.
        /// </summary>
        internal static string BookingThanks {
            get {
                return ResourceManager.GetString("BookingThanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to boka.
        /// </summary>
        internal static string BookLower {
            get {
                return ResourceManager.GetString("BookLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ort.
        /// </summary>
        internal static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du måste ange ett giltigt personnummer.
        /// </summary>
        internal static string CivicNumberError {
            get {
                return ResourceManager.GetString("CivicNumberError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personnummer.
        /// </summary>
        internal static string CivRegNumber {
            get {
                return ResourceManager.GetString("CivRegNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stäng.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kommande tillfällen.
        /// </summary>
        internal static string ComingEvents {
            get {
                return ResourceManager.GetString("ComingEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Företag.
        /// </summary>
        internal static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Företagsinformation.
        /// </summary>
        internal static string CompanyInformation {
            get {
                return ResourceManager.GetString("CompanyInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Företagsnamn.
        /// </summary>
        internal static string CompanyName {
            get {
                return ResourceManager.GetString("CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Företagsnamn saknas.
        /// </summary>
        internal static string CompanyNameMissing {
            get {
                return ResourceManager.GetString("CompanyNameMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bekräfta.
        /// </summary>
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En bekräftelse har skickats till den angivna mailen.
        /// </summary>
        internal static string ConfirmationHasBeenSent {
            get {
                return ResourceManager.GetString("ConfirmationHasBeenSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bekräfta nytt lösenord.
        /// </summary>
        internal static string ConfirmNewPassword {
            get {
                return ResourceManager.GetString("ConfirmNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontaktinformation.
        /// </summary>
        internal static string ContactInformation {
            get {
                return ResourceManager.GetString("ContactInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontaktuppgifter.
        /// </summary>
        internal static string ContactInformation1 {
            get {
                return ResourceManager.GetString("ContactInformation1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kostnad.
        /// </summary>
        internal static string Cost {
            get {
                return ResourceManager.GetString("Cost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kunde inte skapa bokningen, var god försök igen..
        /// </summary>
        internal static string CouldntCreateBookingTryAgain {
            get {
                return ResourceManager.GetString("CouldntCreateBookingTryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kunde inte skapa kunden, var god kontrollera dina uppgifter och försök igen..
        /// </summary>
        internal static string CouldntCreateCustomerTryAgain {
            get {
                return ResourceManager.GetString("CouldntCreateCustomerTryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kursinnehåll.
        /// </summary>
        internal static string CourseContent {
            get {
                return ResourceManager.GetString("CourseContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kursen är fullbokad.
        /// </summary>
        internal static string CourseFullyBooked {
            get {
                return ResourceManager.GetString("CourseFullyBooked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kursmål.
        /// </summary>
        internal static string CourseGoals {
            get {
                return ResourceManager.GetString("CourseGoals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kurser.
        /// </summary>
        internal static string Courses {
            get {
                return ResourceManager.GetString("Courses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kurssida och anmälan.
        /// </summary>
        internal static string CourseSiteAndRegistration {
            get {
                return ResourceManager.GetString("CourseSiteAndRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fel vid skapande av deltagare. Var god logga in igen..
        /// </summary>
        internal static string CreateParticipantErrorLogInAgain {
            get {
                return ResourceManager.GetString("CreateParticipantErrorLogInAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuvarande lösenord.
        /// </summary>
        internal static string CurrentPassword {
            get {
                return ResourceManager.GetString("CurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontaktperson.
        /// </summary>
        internal static string CustomerContact {
            get {
                return ResourceManager.GetString("CustomerContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Företagsuppgifter.
        /// </summary>
        internal static string CustomerInformation {
            get {
                return ResourceManager.GetString("CustomerInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum.
        /// </summary>
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dagar mellan.
        /// </summary>
        internal static string DaysBetween {
            get {
                return ResourceManager.GetString("DaysBetween", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-post.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ogiltigt format på e-post.
        /// </summary>
        internal static string EmailInvalidFormat {
            get {
                return ResourceManager.GetString("EmailInvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-postadress saknas.
        /// </summary>
        internal static string EmailMissing {
            get {
                return ResourceManager.GetString("EmailMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-postadressen är felaktig.
        /// </summary>
        internal static string EmailWrong {
            get {
                return ResourceManager.GetString("EmailWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter at least one {0}.
        /// </summary>
        internal static string EnterAtLeastOneError {
            get {
                return ResourceManager.GetString("EnterAtLeastOneError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fyll i namn på deltagare.
        /// </summary>
        internal static string EnterParticipantName {
            get {
                return ResourceManager.GetString("EnterParticipantName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Något gick fel...vi ber om ursäkt..
        /// </summary>
        internal static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to utvärdering.
        /// </summary>
        internal static string Evaluation {
            get {
                return ResourceManager.GetString("Evaluation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tillfället är fullbokat..
        /// </summary>
        internal static string EventFullyBooked {
            get {
                return ResourceManager.GetString("EventFullyBooked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tillfället är fullbokat!.
        /// </summary>
        internal static string EventFullyBookedEx {
            get {
                return ResourceManager.GetString("EventFullyBookedEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tillfälle.
        /// </summary>
        internal static string EventLower {
            get {
                return ResourceManager.GetString("EventLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tillfällen.
        /// </summary>
        internal static string EventsLower {
            get {
                return ResourceManager.GetString("EventsLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field is required.
        /// </summary>
        internal static string FieldIsRequired {
            get {
                return ResourceManager.GetString("FieldIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field must be checked in order to continue..
        /// </summary>
        internal static string FieldMustBeChecked {
            get {
                return ResourceManager.GetString("FieldMustBeChecked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fel i filtreringen.
        /// </summary>
        internal static string FiltrationError {
            get {
                return ResourceManager.GetString("FiltrationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Förnamn.
        /// </summary>
        internal static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Från.
        /// </summary>
        internal static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to från.
        /// </summary>
        internal static string FromLower {
            get {
                return ResourceManager.GetString("FromLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fullbokat.
        /// </summary>
        internal static string FullyBooked {
            get {
                return ResourceManager.GetString("FullyBooked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fullbokat.
        /// </summary>
        internal static string FullyBookedLower {
            get {
                return ResourceManager.GetString("FullyBookedLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hämta tillfällen.
        /// </summary>
        internal static string GetEvents {
            get {
                return ResourceManager.GetString("GetEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mål.
        /// </summary>
        internal static string Goal {
            get {
                return ResourceManager.GetString("Goal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gå tillbaka till startsidan.
        /// </summary>
        internal static string GoBackToStartPage {
            get {
                return ResourceManager.GetString("GoBackToStartPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gå till sidan för inloggning.
        /// </summary>
        internal static string GoToLoginPage {
            get {
                return ResourceManager.GetString("GoToLoginPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Om kryssrutan saknas betyder det att närvaron är låst då deltagaren redan har fått ett betyg..
        /// </summary>
        internal static string GradeHasBeenSetWarning {
            get {
                return ResourceManager.GetString("GradeHasBeenSetWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Betyg ej angivet.
        /// </summary>
        internal static string GradeNotSet {
            get {
                return ResourceManager.GetString("GradeNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Betyg har uppdaterats..
        /// </summary>
        internal static string GradesUpdated {
            get {
                return ResourceManager.GetString("GradesUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dölj kurser.
        /// </summary>
        internal static string HideCourses {
            get {
                return ResourceManager.GetString("HideCourses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to infotext - halv rad.
        /// </summary>
        internal static string InfoTextHalfRow {
            get {
                return ResourceManager.GetString("InfoTextHalfRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to infotext - hel rad.
        /// </summary>
        internal static string InfoTextWholeRow {
            get {
                return ResourceManager.GetString("InfoTextWholeRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to i.
        /// </summary>
        internal static string InLower {
            get {
                return ResourceManager.GetString("InLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intresseanmälan.
        /// </summary>
        internal static string InterestRegistration {
            get {
                return ResourceManager.GetString("InterestRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intresseanmälan skapad!.
        /// </summary>
        internal static string InterestRegistrationCreated {
            get {
                return ResourceManager.GetString("InterestRegistrationCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Något gick fel. Intresseanmälan ej skapad..
        /// </summary>
        internal static string InterestRegistrationError {
            get {
                return ResourceManager.GetString("InterestRegistrationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid date of birth.
        /// </summary>
        internal static string InvalidBirthDate {
            get {
                return ResourceManager.GetString("InvalidBirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ogiltig utbildningslänk.
        /// </summary>
        internal static string InvalidEducationLink {
            get {
                return ResourceManager.GetString("InvalidEducationLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ogiltig fälttyp.
        /// </summary>
        internal static string InvalidFieldType {
            get {
                return ResourceManager.GetString("InvalidFieldType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ogiltigt nummer.
        /// </summary>
        internal static string InvalidNumber {
            get {
                return ResourceManager.GetString("InvalidNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ogiltigt organisationsnummer.
        /// </summary>
        internal static string InvalidOrganizationalNumber {
            get {
                return ResourceManager.GetString("InvalidOrganizationalNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du måste ange ett giltigt organisationsnummer.
        /// </summary>
        internal static string InvalidOrganizationNumber {
            get {
                return ResourceManager.GetString("InvalidOrganizationNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ogiltigt lösenord.
        /// </summary>
        internal static string InvalidPassword {
            get {
                return ResourceManager.GetString("InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ogiltigt lösenord eller E-post.
        /// </summary>
        internal static string InvalidPasswordOrEmail {
            get {
                return ResourceManager.GetString("InvalidPasswordOrEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid phone number.
        /// </summary>
        internal static string InvalidPhoneNumber {
            get {
                return ResourceManager.GetString("InvalidPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faktura.
        /// </summary>
        internal static string Invoice {
            get {
                return ResourceManager.GetString("Invoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fakturaadress.
        /// </summary>
        internal static string InvoiceAddress {
            get {
                return ResourceManager.GetString("InvoiceAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fakturaort.
        /// </summary>
        internal static string InvoiceCity {
            get {
                return ResourceManager.GetString("InvoiceCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sista ansökningsdatum.
        /// </summary>
        internal static string LastApplicationDate {
            get {
                return ResourceManager.GetString("LastApplicationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sista ansökningsdag.
        /// </summary>
        internal static string LastApplicationDay {
            get {
                return ResourceManager.GetString("LastApplicationDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antingen så har sista anmälningsdag passerat eller så har tillfället tagits bort..
        /// </summary>
        internal static string LastDatePassedOrEventRemoved {
            get {
                return ResourceManager.GetString("LastDatePassedOrEventRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Efternamn.
        /// </summary>
        internal static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inloggad som:.
        /// </summary>
        internal static string LoggedInAs {
            get {
                return ResourceManager.GetString("LoggedInAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logga in.
        /// </summary>
        internal static string LogIn {
            get {
                return ResourceManager.GetString("LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du måste logga in för att kunna ändra ditt lösenord.
        /// </summary>
        internal static string LogInChangePassword {
            get {
                return ResourceManager.GetString("LogInChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logga in i &apos;Mina Sidor&apos;.
        /// </summary>
        internal static string LogIntoMyPages {
            get {
                return ResourceManager.GetString("LogIntoMyPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logga ut.
        /// </summary>
        internal static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gjorda bokningar.
        /// </summary>
        internal static string MadeBookings {
            get {
                return ResourceManager.GetString("MadeBookings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sätt närvaro.
        /// </summary>
        internal static string MarkAttendance {
            get {
                return ResourceManager.GetString("MarkAttendance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Markera de deltagare som är närvarande..
        /// </summary>
        internal static string MarkAttendingParticipants {
            get {
                return ResourceManager.GetString("MarkAttendingParticipants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Markera de deltagare som är godkända..
        /// </summary>
        internal static string MarkPassedParticipants {
            get {
                return ResourceManager.GetString("MarkPassedParticipants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Markera / avmarkera alla deltagare..
        /// </summary>
        internal static string MarkUnmarkAllParticipants {
            get {
                return ResourceManager.GetString("MarkUnmarkAllParticipants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mätare.
        /// </summary>
        internal static string Meter {
            get {
                return ResourceManager.GetString("Meter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobil.
        /// </summary>
        internal static string Mobile {
            get {
                return ResourceManager.GetString("Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobilnummer saknas.
        /// </summary>
        internal static string MobileMissing {
            get {
                return ResourceManager.GetString("MobileMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to till kurs.
        /// </summary>
        internal static string MoreCourseLower {
            get {
                return ResourceManager.GetString("MoreCourseLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to till kurser.
        /// </summary>
        internal static string MoreCoursesLower {
            get {
                return ResourceManager.GetString("MoreCoursesLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du måste kryssa i rutan.
        /// </summary>
        internal static string MustCheckCheckBox {
            get {
                return ResourceManager.GetString("MustCheckCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Måste fylla i e-post.
        /// </summary>
        internal static string MustEnterEmail {
            get {
                return ResourceManager.GetString("MustEnterEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Måste fylla i förnamn.
        /// </summary>
        internal static string MustEnterFirstName {
            get {
                return ResourceManager.GetString("MustEnterFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Måste fylla i efternamn.
        /// </summary>
        internal static string MustEnterLastName {
            get {
                return ResourceManager.GetString("MustEnterLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Måste fylla i telefonnummer.
        /// </summary>
        internal static string MustEnterPhoneNumber {
            get {
                return ResourceManager.GetString("MustEnterPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fyll i en giltig e-post.
        /// </summary>
        internal static string MustEnterValidEmail {
            get {
                return ResourceManager.GetString("MustEnterValidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du måste välja ett alternativ.
        /// </summary>
        internal static string MustSelectAnOption {
            get {
                return ResourceManager.GetString("MustSelectAnOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du måste välja ett pris.
        /// </summary>
        internal static string MustSelectPrice {
            get {
                return ResourceManager.GetString("MustSelectPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du måste ange adress.
        /// </summary>
        internal static string MustSubmitAddress {
            get {
                return ResourceManager.GetString("MustSubmitAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du måste ange ort.
        /// </summary>
        internal static string MustSubmitCity {
            get {
                return ResourceManager.GetString("MustSubmitCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du måste ange personnummer.
        /// </summary>
        internal static string MustSubmitCivRegNumber {
            get {
                return ResourceManager.GetString("MustSubmitCivRegNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du måste ange företagsnamn.
        /// </summary>
        internal static string MustSubmitCompanyName {
            get {
                return ResourceManager.GetString("MustSubmitCompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du måste ange ditt nuvarande lösenord \n.
        /// </summary>
        internal static string MustSubmitCurrentPassword {
            get {
                return ResourceManager.GetString("MustSubmitCurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du måste ange e-post.
        /// </summary>
        internal static string MustSubmitEmail {
            get {
                return ResourceManager.GetString("MustSubmitEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du måste ange förnamn.
        /// </summary>
        internal static string MustSubmitFirstName {
            get {
                return ResourceManager.GetString("MustSubmitFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du måste ange efternamn.
        /// </summary>
        internal static string MustSubmitLastName {
            get {
                return ResourceManager.GetString("MustSubmitLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du måste ange organisationsnummer.
        /// </summary>
        internal static string MustSubmitOrganizationalNumber {
            get {
                return ResourceManager.GetString("MustSubmitOrganizationalNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du måste ange telefonnummer.
        /// </summary>
        internal static string MustSubmitPhone {
            get {
                return ResourceManager.GetString("MustSubmitPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du måste ange {0}.
        /// </summary>
        internal static string MustSubmitText {
            get {
                return ResourceManager.GetString("MustSubmitText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du måste ange en giltig e-post.
        /// </summary>
        internal static string MustSubmitValidEmail {
            get {
                return ResourceManager.GetString("MustSubmitValidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du måste ange postnummer.
        /// </summary>
        internal static string MustSubmitZipCode {
            get {
                return ResourceManager.GetString("MustSubmitZipCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to upload a file for {0}.
        /// </summary>
        internal static string MustUploadFile {
            get {
                return ResourceManager.GetString("MustUploadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mina sidor.
        /// </summary>
        internal static string MyPages {
            get {
                return ResourceManager.GetString("MyPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Namn.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Namn saknas.
        /// </summary>
        internal static string NameMissing {
            get {
                return ResourceManager.GetString("NameMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Namnge namnlösa {0}st.
        /// </summary>
        internal static string NameNamelessNr {
            get {
                return ResourceManager.GetString("NameNamelessNr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kr.
        /// </summary>
        internal static string NatCurrShortLower {
            get {
                return ResourceManager.GetString("NatCurrShortLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sek.
        /// </summary>
        internal static string NationalCurrencyShortLower {
            get {
                return ResourceManager.GetString("NationalCurrencyShortLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nytt stycke.
        /// </summary>
        internal static string NewParagraph {
            get {
                return ResourceManager.GetString("NewParagraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nytt lösenord.
        /// </summary>
        internal static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nästa.
        /// </summary>
        internal static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inga bokningar hittades.
        /// </summary>
        internal static string NoBookingsFound {
            get {
                return ResourceManager.GetString("NoBookingsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inga framtida kurser.
        /// </summary>
        internal static string NoComingCourses {
            get {
                return ResourceManager.GetString("NoComingCourses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kostnadsfri.
        /// </summary>
        internal static string NoCost {
            get {
                return ResourceManager.GetString("NoCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inga kurser idag.
        /// </summary>
        internal static string NoCoursesToday {
            get {
                return ResourceManager.GetString("NoCoursesToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inga deltagare.
        /// </summary>
        internal static string NoParticipants {
            get {
                return ResourceManager.GetString("NoParticipants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inga passerade kurser.
        /// </summary>
        internal static string NoPreviousCourses {
            get {
                return ResourceManager.GetString("NoPreviousCourses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inget pris valt.
        /// </summary>
        internal static string NoPriceSelected {
            get {
                return ResourceManager.GetString("NoPriceSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ej ankommen.
        /// </summary>
        internal static string NotArrived {
            get {
                return ResourceManager.GetString("NotArrived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ej närvarande.
        /// </summary>
        internal static string NotAttending {
            get {
                return ResourceManager.GetString("NotAttending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Det finns inte tillräckligt med platser kvar på kursen.
        /// </summary>
        internal static string NotEnoughSeatsLeft {
            get {
                return ResourceManager.GetString("NotEnoughSeatsLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meddelande.
        /// </summary>
        internal static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ej betygsatt.
        /// </summary>
        internal static string NotGraded {
            get {
                return ResourceManager.GetString("NotGraded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ej Inloggad.
        /// </summary>
        internal static string NotLoggedIn {
            get {
                return ResourceManager.GetString("NotLoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ej betald.
        /// </summary>
        internal static string NotPaid {
            get {
                return ResourceManager.GetString("NotPaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ej godkända.
        /// </summary>
        internal static string NotPassed {
            get {
                return ResourceManager.GetString("NotPassed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Det finns inga kommande tillfällen för denna utbildning.
        /// </summary>
        internal static string NoUpcomingEventsExist {
            get {
                return ResourceManager.GetString("NoUpcomingEventsExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inget värde angett.
        /// </summary>
        internal static string NoValueGiven {
            get {
                return ResourceManager.GetString("NoValueGiven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inget värde angivet.
        /// </summary>
        internal static string NoValueGiven2 {
            get {
                return ResourceManager.GetString("NoValueGiven2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to exkl moms.
        /// </summary>
        internal static string NoVatLower {
            get {
                return ResourceManager.GetString("NoVatLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to st närvarande.
        /// </summary>
        internal static string NrAttending {
            get {
                return ResourceManager.GetString("NrAttending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to st.
        /// </summary>
        internal static string NrLower {
            get {
                return ResourceManager.GetString("NrLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to st namnlösa.
        /// </summary>
        internal static string NrNameless {
            get {
                return ResourceManager.GetString("NrNameless", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} deltagare.
        /// </summary>
        internal static string NrParticipants {
            get {
                return ResourceManager.GetString("NrParticipants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to st deltagare.
        /// </summary>
        internal static string NrParticipantsLower {
            get {
                return ResourceManager.GetString("NrParticipantsLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antal deltagare.
        /// </summary>
        internal static string NumberParticipants {
            get {
                return ResourceManager.GetString("NumberParticipants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ditt gamla lösenord stämmer inte.
        /// </summary>
        internal static string OldPasswordInvalid {
            get {
                return ResourceManager.GetString("OldPasswordInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to envalsfråga.
        /// </summary>
        internal static string OneChoiceQuestion {
            get {
                return ResourceManager.GetString("OneChoiceQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to envalsfråga horisontell.
        /// </summary>
        internal static string OneChoiceQuestionHorizontal {
            get {
                return ResourceManager.GetString("OneChoiceQuestionHorizontal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 till kurs.
        /// </summary>
        internal static string OneMoreCourse {
            get {
                return ResourceManager.GetString("OneMoreCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Det finns endast {0} platser kvar på tillfället.
        /// </summary>
        internal static string OnlyNrSeatsLeft {
            get {
                return ResourceManager.GetString("OnlyNrSeatsLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organisationsnummer.
        /// </summary>
        internal static string OrganizationalNumber {
            get {
                return ResourceManager.GetString("OrganizationalNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organisatör.
        /// </summary>
        internal static string Organizer {
            get {
                return ResourceManager.GetString("Organizer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Övrig information.
        /// </summary>
        internal static string OtherInformation {
            get {
                return ResourceManager.GetString("OtherInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Våra kurser.
        /// </summary>
        internal static string OurCourses {
            get {
                return ResourceManager.GetString("OurCourses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sida.
        /// </summary>
        internal static string Page {
            get {
                return ResourceManager.GetString("Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sidan kunde inte hittas.
        /// </summary>
        internal static string PageNotFound {
            get {
                return ResourceManager.GetString("PageNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Betald.
        /// </summary>
        internal static string Paid {
            get {
                return ResourceManager.GetString("Paid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deltagare.
        /// </summary>
        internal static string Participant {
            get {
                return ResourceManager.GetString("Participant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deltagare ändrad.
        /// </summary>
        internal static string ParticipantChanged {
            get {
                return ResourceManager.GetString("ParticipantChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deltagare avbokad.
        /// </summary>
        internal static string ParticipantRemoved {
            get {
                return ResourceManager.GetString("ParticipantRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deltagare skapade.
        /// </summary>
        internal static string ParticipantsCreated {
            get {
                return ResourceManager.GetString("ParticipantsCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antal deltagare måste vara ett positivt numeriskt värde.
        /// </summary>
        internal static string ParticipantsMustBePositive {
            get {
                return ResourceManager.GetString("ParticipantsMustBePositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deltagare namngivna.
        /// </summary>
        internal static string ParticipantsNamed {
            get {
                return ResourceManager.GetString("ParticipantsNamed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kunde inte namnge deltagare.
        /// </summary>
        internal static string ParticipantsNamingError {
            get {
                return ResourceManager.GetString("ParticipantsNamingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deltagare på bokningen.
        /// </summary>
        internal static string ParticipantsOnBooking {
            get {
                return ResourceManager.GetString("ParticipantsOnBooking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Godkända.
        /// </summary>
        internal static string Passed {
            get {
                return ResourceManager.GetString("Passed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lösenord.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nytt lösenord sparat!.
        /// </summary>
        internal static string PasswordSaved {
            get {
                return ResourceManager.GetString("PasswordSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dina lösenord matchar inte \n.
        /// </summary>
        internal static string PasswordsNotMatching {
            get {
                return ResourceManager.GetString("PasswordsNotMatching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Betalningsinformation.
        /// </summary>
        internal static string PaymentInformation {
            get {
                return ResourceManager.GetString("PaymentInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Betalningsmetod.
        /// </summary>
        internal static string PaymentMethod {
            get {
                return ResourceManager.GetString("PaymentMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personalsidor.
        /// </summary>
        internal static string PersonalPages {
            get {
                return ResourceManager.GetString("PersonalPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon.
        /// </summary>
        internal static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefonnummer.
        /// </summary>
        internal static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefonnumret är i felaktigt format.
        /// </summary>
        internal static string PhoneNumberWrongFormat {
            get {
                return ResourceManager.GetString("PhoneNumberWrongFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plats:.
        /// </summary>
        internal static string Place {
            get {
                return ResourceManager.GetString("Place", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Förkunskaper.
        /// </summary>
        internal static string Prerequisites {
            get {
                return ResourceManager.GetString("Prerequisites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tidigare kurser.
        /// </summary>
        internal static string PreviousCourses {
            get {
                return ResourceManager.GetString("PreviousCourses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pris.
        /// </summary>
        internal static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skriv ut diplom.
        /// </summary>
        internal static string PrintDiploma {
            get {
                return ResourceManager.GetString("PrintDiploma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skriv ut utvärderingsstatistik.
        /// </summary>
        internal static string PrintEvaluationStatistics {
            get {
                return ResourceManager.GetString("PrintEvaluationStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skriv ut deltagarlista.
        /// </summary>
        internal static string PrintParticipantList {
            get {
                return ResourceManager.GetString("PrintParticipantList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Denna fråga är obligatorisk.
        /// </summary>
        internal static string QuestionIsMandatory {
            get {
                return ResourceManager.GetString("QuestionIsMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Om ni har frågor eller inte mottagit någon bekräftelse inom loppet av 24 timmar var vänlig kontakta.
        /// </summary>
        internal static string QuestionsContactUs {
            get {
                return ResourceManager.GetString("QuestionsContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Läs mer.
        /// </summary>
        internal static string ReadMore {
            get {
                return ResourceManager.GetString("ReadMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kunde inte avboka deltagaren, var god ladda om sidan och försök igen om problemet kvarstår.
        /// </summary>
        internal static string RemoveParticipantErrorReloadPage {
            get {
                return ResourceManager.GetString("RemoveParticipantErrorReloadPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rumsnamn.
        /// </summary>
        internal static string RoomName {
            get {
                return ResourceManager.GetString("RoomName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to radbrytning.
        /// </summary>
        internal static string RowBreak {
            get {
                return ResourceManager.GetString("RowBreak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kör init först.
        /// </summary>
        internal static string RunInitFirst {
            get {
                return ResourceManager.GetString("RunInitFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spara.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spara lösenord.
        /// </summary>
        internal static string SavePassword {
            get {
                return ResourceManager.GetString("SavePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genom att spara så kommer betygen att låsas..
        /// </summary>
        internal static string SavingGradesWarning {
            get {
                return ResourceManager.GetString("SavingGradesWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schema.
        /// </summary>
        internal static string Schedule {
            get {
                return ResourceManager.GetString("Schedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sök.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sökningen gav inga resultat..
        /// </summary>
        internal static string SearchGaveNoResults {
            get {
                return ResourceManager.GetString("SearchGaveNoResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plats kvar.
        /// </summary>
        internal static string SeatLeftLower {
            get {
                return ResourceManager.GetString("SeatLeftLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Platser kvar:.
        /// </summary>
        internal static string SeatsLeft {
            get {
                return ResourceManager.GetString("SeatsLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to platser kvar.
        /// </summary>
        internal static string SeatsLeftLower {
            get {
                return ResourceManager.GetString("SeatsLeftLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Välj närvarostatus.
        /// </summary>
        internal static string SelectArrivalStatus {
            get {
                return ResourceManager.GetString("SelectArrivalStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --Välj Kategori--.
        /// </summary>
        internal static string SelectCategory {
            get {
                return ResourceManager.GetString("SelectCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Välj betyg.
        /// </summary>
        internal static string SelectGrade {
            get {
                return ResourceManager.GetString("SelectGrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --Välj Ämne--.
        /// </summary>
        internal static string SelectSubject {
            get {
                return ResourceManager.GetString("SelectSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skicka.
        /// </summary>
        internal static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sätt betyg.
        /// </summary>
        internal static string SetGrade {
            get {
                return ResourceManager.GetString("SetGrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Betygsättning.
        /// </summary>
        internal static string SetGrades {
            get {
                return ResourceManager.GetString("SetGrades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sortera på:.
        /// </summary>
        internal static string SortOn {
            get {
                return ResourceManager.GetString("SortOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  ({0} närvarande).
        /// </summary>
        internal static string SpecNrAttending {
            get {
                return ResourceManager.GetString("SpecNrAttending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Målgrupp.
        /// </summary>
        internal static string TargetGroup {
            get {
                return ResourceManager.GetString("TargetGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Till.
        /// </summary>
        internal static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dagens kurser.
        /// </summary>
        internal static string TodaysCourses {
            get {
                return ResourceManager.GetString("TodaysCourses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle navigation.
        /// </summary>
        internal static string ToggleNavigation {
            get {
                return ResourceManager.GetString("ToggleNavigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to till.
        /// </summary>
        internal static string ToLower {
            get {
                return ResourceManager.GetString("ToLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Totalpris.
        /// </summary>
        internal static string TotalPrice {
            get {
                return ResourceManager.GetString("TotalPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ett oväntat fel uppstod när bokningen skulle skapas, var god försök igen..
        /// </summary>
        internal static string UnexpectedBookingError {
            get {
                return ResourceManager.GetString("UnexpectedBookingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ett oväntat fel uppstod när bokningen skulle skapas, var god ladda om sidan och försök igen..
        /// </summary>
        internal static string UnexpectedBookingErrorReloadPage {
            get {
                return ResourceManager.GetString("UnexpectedBookingErrorReloadPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Okänt frågetypsid.
        /// </summary>
        internal static string UnknownQuestionTypeID {
            get {
                return ResourceManager.GetString("UnknownQuestionTypeID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kommande bokningar.
        /// </summary>
        internal static string UpcomingBookings {
            get {
                return ResourceManager.GetString("UpcomingBookings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kommande kurser.
        /// </summary>
        internal static string UpcomingCourses {
            get {
                return ResourceManager.GetString("UpcomingCourses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vyn saknas!.
        /// </summary>
        internal static string ViewMissing {
            get {
                return ResourceManager.GetString("ViewMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fel vid namngivning av deltagare. Var god kontrollera uppgifterna.
        /// </summary>
        internal static string WrongParticipantNamingControlInformation {
            get {
                return ResourceManager.GetString("WrongParticipantNamingControlInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fel vid namngivning av deltagare. Var god logga in igen..
        /// </summary>
        internal static string WrongParticipantNamingLogInAgain {
            get {
                return ResourceManager.GetString("WrongParticipantNamingLogInAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postnummer.
        /// </summary>
        internal static string ZipCode {
            get {
                return ResourceManager.GetString("ZipCode", resourceCulture);
            }
        }
    }
}
